### ISSUE TITLE
'items per page' option not saved in next query when user pass to next page

### ISSUE THREAD

**Issue by foxmuldercp** [Sology/smart_listing#101]
Case:
Open my collection - ok
Set 100 items per page - collection reloaded ok
Press one of page buttons - collection showed as first default (10) items

**Comment by ljachymczyk** [comment]
Hello,
This scenario works in the showcase (http://showcase.sology.eu/smart_listing). Do you use the latest version (1.2.0)?

**Comment by foxmuldercp** [comment]
# gem list | grep list
smart_listing (1.2.0)

**Comment by foxmuldercp** [comment]
I don't set save items per page in cookies
