### ISSUE TITLE
Sorting direction change when joining tables on activerecord associations

### ISSUE THREAD

**Issue by chrisjeon** [Sology/smart_listing#109]
It sorts asc initiallly, but does not change directions afterwards and does not sort afterwards.

**Comment by chrisjeon** [comment]
I see where it's breaking, I'll submit a quick PR

**Comment by chrisjeon** [comment]
PR is https://github.com/Sology/smart_listing/pull/110

**Comment by ljachymczyk** [comment]
Sorry, can't merge it. See my explanation in the PR.
