### ISSUE TITLE
Database Unique Constraints 

### ISSUE THREAD

**Issue by bombertroop** [Sology/smart_listing#116]
Hi guys,

I have database unique constraints for one field, when I change the value of that field with a field value that already exists in the database unexpectedly the object was considered valid whereas the object should not be valid and should be render form page, this cased occured in the update action, here is my update.js.erb content
<%= smart_listing_item :brands, :update, @brand, 
                       @brand.valid? ? "brands/brand" : "brands/form" %>
so valid? method ignored ActiveRecord::RecordNotUnique error, do you guys have the solution for this case? I really appreciate for the help, many thanks

**Comment by ljachymczyk** [comment]
This seems to be a problem with your model validation, not SmartListing. Please check if your validation works outside SmartListing.
