### ISSUE TITLE
undefined method `per'

### ISSUE THREAD

**Issue by dkru** [Sology/smart_listing#119]
I have problem with this error on Rails 4.2
I fix this error in file lib/smart_listing.rb on row 95 and row 106 with change _per_ to _per_page_

`95       @collection = ::Kaminari.paginate_array(@collection).page(@page).per(@per_page)`
`...`
`106     @collection = @collection.page(@page).per(@per_page)`

request to developer: please fix this error. Rails 4.2 Active record not have method _per_

**Comment by cpg** [comment]
This appears to be an issue still at this time (with Rails 5.2 here at least). Should it be open?

The solution you suggest seems to work. Here is [a PR](https://github.com/Sology/smart_listing/pull/153), for it.
