### ISSUE TITLE
pagination and sorting for some reason doesn't work...

### ISSUE THREAD

**Issue by dannyvanhoof** [Sology/smart_listing#123]
although it looks like I'm doing exactly the same as in your showcase "sorting" demo, the pagination buttons on my page only show pagination, but not the current sort: `http://localhost:3000/projects?projects_smart_listing%5Bpage%5D=3`. Sorting works fine, as long as I don't switch to another page. Once a go to another page, the sorting is "forgotten". Any idea why this might be the case?

**Comment by ljachymczyk** [comment]
Hello @dannyvanhoof 
Can you share your rails & ruby versions?
