### ISSUE TITLE
How to change default number of records in smart listing from 10 to 50.

### ISSUE THREAD

**Issue by abhsss96** [Sology/smart_listing#127]
I tried to change default number of records per page but I am unable to change it.  I tried changing config/intializers/smart_listing.rb 

`SmartListing.configure do |config|
  config.global_options({
    #:param_names  => {                                              # param names
      #:page                         => :page,
      #:per_page                     => :per_page,
      #:sort                         => :sort,
    #},
    #:array                          => false,                       # controls whether smart list should be using arrays or AR collections
    #:max_count                      => 50                         # limit number of rows
    #:unlimited_per_page             => false,                       # allow infinite page size
    #:paginate                       => true,                        # allow pagination
    #:memorize_per_page              => false,                       # save per page settings in the cookie
    #:page_sizes                     => DEFAULT_PAGE_SIZES          # set available page sizes array
    :kaminari_options               => { :theme => "smart_listing", :default_per_page => 50} # Kaminari's paginate helper options
    #:sort_dirs                      => [nil, "asc", "desc"],        # Default sorting directions cycle of sortables
  })`

**Comment by lienha** [comment]
In users_controller.rb, you can do this:
smart_listing_create :users, User.active, partial: "list", page_sizes: [50, 100]
