### ISSUE TITLE
smart_listing_collection

### ISSUE THREAD

**Issue by rdosramos** [Sology/smart_listing#128]
Hi Sology,

Im trying to use your gem in a project, but i keep crashing with the following error:

**undefined local variable or method `smart_listing_collection' for #<UserController>**

The place when the call presents the error is the controller's index method:
@users = smart_listing_create partial: "users/listing".

In the head of the controller, right below "class UsersController < ApplicationController", i added
	"include SmartListing::Helper::ControllerExtensions
	helper  SmartListing::Helper"
as instructed.

**Comment by wynksaiddestroy** [comment]
Please read the [instructions](https://github.com/Sology/smart_listing#usage) carefully. You forgot to provide a ActiveRecord scope like this:

    @users = smart_listing_create(:users, User.active, partial: "users/listing")

**Comment by ardahaal** [comment]
Thanks @wynksaiddestroy for answering :)
