### ISSUE TITLE
Query COUNT(*) takes too long

### ISSUE THREAD

**Issue by Kani999** [Sology/smart_listing#133]
Hello,
With every render of page COUNT(*) is sent to database.
We have database with a lot of rows.
Sometimes count takes from 300 - 1000 ms.

Is there any way how to get number of rows from collection?

my idea is something like:

Instead of   rows.count which runs SQL query, use rows.length which return number of rows as well?

**Comment by bval** [comment]
Gonna guess you're using Postgres? [This might be interesting to you](https://wiki.postgresql.org/wiki/Slow_Counting).

For users of every other database `COUNT(*)` is a faster implementation. I would be opposed to doing this in Ruby for those users. It would be smarter to either overload the way the count query is implemented only for Postgres or to allow the count method to be overridden somehow.

**Comment by Kani999** [comment]
Iam using MySQL.
My Bad.
I was thinking that the number of elements could be obtained from the array of objects. BUT array of objects are limited by SQL clause with Limit, so the number of elements in the collection does not match the number of rows in DB.

Iam closing the ticket. 
Thanks.
