### ISSUE TITLE
Using wrong ajax URL when turbolinks activated

### ISSUE THREAD

**Issue by lacco** [Sology/smart_listing#20]
Steps to reproduce in an app with turbolinks:

1. Visit a page that doesn't use *smart_listing* (e.g. faq page, ```/faq```)
2. Click on a link that leads to the page using *smart_listing* (e.g. ```/books```)
3. Click on a filter or anything that causes a reload of the results

When using the standard *smart_listing* configuration, it tries to load the results from ```/faq?filter1=val&filter2=val```. Internally, *smart_listing* is calling ```$.rails.handleRemote``` which cannot find a proper URL/ href so that ```$.ajax``` is using a cached version of ```location.href``` (which points the initially loaded URL ```/faq```).

Workaround: Adding an explicit ```href``` to ```smart_listing_create``` call: ```smart_listing_create ..., href: books_path```

Potential fix to discuss: The default value for ```href``` is ```nil``` (https://github.com/Sology/smart_listing/blob/master/lib/smart_listing.rb#L35), perhaps we should set it the current path via ```url_for```?

**Comment by wynksaiddestroy** [comment]
I somehow messed up the first pull request. Is there still a demand of an example app that shows the problem?

**Comment by ljachymczyk** [comment]
Thanks!
