### ISSUE TITLE
undefined method `like' for ....

### ISSUE THREAD

**Issue by bkd** [Sology/smart_listing#28]
Hi, 

Firstly great gem!

I'm getting 

undefined method `like' for #Assignment::ActiveRecord_Relation:0x007f783b3c9d70 

Any ideas? Rails 4.1

**Comment by ums-uk** [comment]
# Note: `like` method here is not built-in Rails scope. You need to define it by yourself. - Please explain this or at least provide an example of your scope

**Comment by ardahaal** [comment]
https://github.com/Sology/smart_listing/issues/42#issuecomment-151458815
