### ISSUE TITLE
Simplification and refactoring

### ISSUE THREAD

**Issue by GCorbel** [Sology/smart_listing#31]
Hi,

I think the project needs a simplification. It would be perfect if, to do an admin interface, we just have to do this : 

```
class UserController < ApplicationController
  smart_listing :crud
end
```

With this simple function call, the controller must have default actions which have the views to do a in place editing like in [the demo](http://showcase.sology.eu/smart_listing).

To have a simple list, it should be possible to replace `smart_listing :crud` by `smart_listing :list`. All actions and views must to be overwritable.

I can pass some times to do it but, before to start, I need unit tests and acceptances specs. I also need to have a support from Sology.

Please, can you do the tests?

Thanks!

**Comment by ljachymczyk** [comment]
Closing as this has been very long time ago and is probably not valid any more.
