### ISSUE TITLE
Bootstrap checkbox buttons not changing params to off

### ISSUE THREAD

**Issue by thisislorne** [Sology/smart_listing#33]
Hey! Awesome gem... 

I have implemented the following with Bootstraps Checkbox buttons.. (http://getbootstrap.com/javascript/#buttons)

![screen shot 2014-09-29 at 3 09 18 am](https://cloud.githubusercontent.com/assets/7201964/4434491/1c7091a0-4719-11e4-95ab-61f84ee8b89e.png)

After toggling the buttons a few times, I am getting a URL ending in this... "all=on&pc=on&leaders=on&staff=on&male=on&filter="

Essentially, even though the state of the button is now 'off' the value in params is still 'on'

Any ideas?

Thanks.

**Comment by danieljacobarcher** [comment]
I'm getting the same issue, and not using bootstrap. Anyone else able to reproduce, or @thisislorne did you fix it?

**Comment by wynksaiddestroy** [comment]
I can reproduce this issue as well. Even a simple check box like `= check_box_tag :show_all` won't work properly.

**Comment by ljachymczyk** [comment]
I think you may need to use also hidden field before checkbox field as described in 'Gotcha' here: https://apidock.com/rails/ActionView/Helpers/FormHelper/check_box
