### ISSUE TITLE
Not compatible with Mongoid

### ISSUE THREAD

**Issue by deanpapastrat** [Sology/smart_listing#34]
So, although this works amazingly well with ActiveRecord, I was concerned because I could not use this gem. So, I made [this fork](https://github.com/deanpapastrat/smart_listing), but I'm still not 100% sure of its backwards compatibility with ActiveRecord. Would this team be willing to support Mongoid and ActiveRecord, or should I continue to pursue this on my own?

**Comment by ljachymczyk** [comment]
Hello @deanpapastrat I don't think we have enough time to support Mongoid. But if you managed to get it running, please consider creating a pull request.
