### ISSUE TITLE
kaminari pagination views

### ISSUE THREAD

**Issue by nodrog** [Sology/smart_listing#39]
Hi 

This is a truly awesome gem, just what i have been looking for.

Only one issue that i have which is how i can override the kaminari views.

I have generated them as kaminari docs suggest, they are just never used.

i really just need to make them not center align and have the class pagination-sm.

Any thoughts?

And many thanks again for the gem.

**Comment by dudo** [comment]
kaminari_options: { theme: 'bootstrap3' }

move the stuff from views/kaminari to views/kaminari/bootstrap3
then change what you need in the views/kaminari/bootstrap3/paginator.html file

**Comment by ljachymczyk** [comment]
@nodrog, let me know if @dudo's tip works.

**Comment by gdurelle** [comment]
I just tried it. it works. Thanks ! :)
