### ISSUE TITLE
Filter inputs fire off excessive requests to backend when gaining focus

### ISSUE THREAD

**Issue by bkd** [Sology/smart_listing#41]
Currently using a filter as per example

  .filter.input-append
    = text_field_tag :filter, '', class: "search", placeholder: "Type name here", autocomplete: "off"
    %button.btn.disabled{type: "submit"}
      %i.icon.icon-search

When ever the page containing the filter input gains or loses focus it fires off the request to the backend to retrieve the data. It would make sense to change this so that upon only a keypress up or if the value has actually changed that it sends the request.

Im not sure if there is a use case for it to re send the request every time the page gains focus, for most users tabbing between browser pages is common and its starting to send enormous amounts of traffic without real value.

**Comment by danieljacobarcher** [comment]
+1 It's actually firing on every keypress, as well as on focus. Can we change this to only be on keyup for characters, ignoring things like arrow key presses, using control, command, or shift keys etc.?

cc: @ljachymczyk

**Comment by danieljacobarcher** [comment]
@bkd I forked it and made some changes to accommodate this, would be great to get others feedback:
https://github.com/danieljacobarcher/smart_listing

**Comment by bkd** [comment]
Nice work Daniel

**Comment by danieljacobarcher** [comment]
@bkd Just created a PR https://github.com/Sology/smart_listing/pull/66 with it included.

**Comment by bkd** [comment]
Nice work, cant wait to get back to the home to test it out after my day's
work. seems like you have most of it solved

**Comment by mahendhar9** [comment]
Hello. I too want to fix this issue in my app. Is there a quick fix for now?
Thanks

**Comment by bkd** [comment]
Yes did u check the forked versions

**Comment by bkd** [comment]
Check Daniel Archers repo

**Comment by mahendhar9** [comment]
Thank you @bkd

**Comment by ljachymczyk** [comment]
@dja Please create separate PR with changes related only to this issue.
