### ISSUE TITLE
Can't use filters

### ISSUE THREAD

**Issue by kkerley** [Sology/smart_listing#42]
Can you explain why following your examples exactly for the filtering continues to result in either:

undefined method `like' for #<Array
or
undefined method `like' for #<ActiveRecord::Relation
?

I've tried using Model.all and Model.scope and it's the same issue every time. It's getting extremely frustrating to try and figure out why I'm forced to set my smart_listing_collection as array: true but then can't use filtering. And if I turn array: true off, I get 

undefined method `page' for #<Array:

What is the trick to using filters on my models? I don't want to use a scope, I just want to return all records in my smart_listing table and allow users to filter by name or year (it's a collection of music albums).

**Comment by kkerley** [comment]
I looked at some closed issues and see someone else brought up this exact same thing. I love how in the examples in both the README.md and the sample site with working examples both nonchalantly use the .like method as though it's part of smart_listing, but in reality, it's some proprietary method that you wrote and didn't think was important to note as being something that isn't included with the gem, nor that including the method anywhere might be beneficial for people to look at and use as a starting point. I've wasted 3 hours trying to get this to work and I can't get it. And now I just don't care anymore.

**Comment by ums-uk** [comment]
Any solutions for this - it's very annoying?

**Comment by ardahaal** [comment]
Hi, check out my smart_listing example. Currently I am testing more complex sorting and filtering, but this 'like' method is only for the filtering collection based on query. If You want to list all records just don't use it. Anyway 'like' method can look like this and should be in model:
`scope :like, ->(args) { where("email like '%#{args}%' OR name like '%#{args}%' OR surname like '%#{args}%'")}`
