### ISSUE TITLE
duplicated key :href at lib/smart_listing/config.rb

### ISSUE THREAD

**Issue by fake-or-dead** [Sology/smart_listing#45]
for get rid of annoying warning 

https://github.com/Sology/smart_listing/blob/master/lib/smart_listing/config.rb#L76
https://github.com/Sology/smart_listing/blob/master/lib/smart_listing/config.rb#L83

**Comment by wynksaiddestroy** [comment]
I already created pull request #43 that hopefully fixes the warning.

**Comment by ljachymczyk** [comment]
#43 fixes that.
