### ISSUE TITLE
[bug] in-place edit: The new item form cannot be cancelled

### ISSUE THREAD

**Issue by ninovanhooff** [Sology/smart_listing#48]
This bug is present in the showcase as well

1. Go to http://showcase.sology.eu/smart_listing
2. In the in-place editing section, click new item
3. Click cancel

Nothing happens, while I expect the form to be hidden and the .new-item-action to be shown

**Comment by ljachymczyk** [comment]
Yes, there was a bug and it is fixed already in v1.1.1. 

Just deployed the showcase.

**Comment by ninovanhooff** [comment]
Confirned fixed
