### ISSUE TITLE
It looks like the destroy popover has a hard coded Yes and No?

### ISSUE THREAD

**Issue by dannyvanhoof** [Sology/smart_listing#50]
Is there a way to also get this localized somehow?

**Comment by ljachymczyk** [comment]
Hi,
You can always define your own confirmation function and reassign it to `$.fn.smart_listing.showConfirmation`

**Comment by ninovanhooff** [comment]
I would also like to be able to change this in the I18n or smart_listing intiializer. Overwriting the complete showConfirmation method seems extreme and prone to breakage. Hard coding is bad, mkay?

**Comment by ljachymczyk** [comment]
Well, localizing javascript code seems to be overkill for small library like smart_listing. So if you want to have showConfirmation localized, you should overwrite it and use your localization framework there.
