### ISSUE TITLE
remote: true links within the list grey out the list

### ISSUE THREAD

**Issue by dudo** [Sology/smart_listing#51]
I have some links in a list that fire a modal, and make an ajax call to fill in the info. They're behaving like the sort links, and making the list grey out... but it won't 'ungrey' until I refresh the page, or resort.

![screen shot 2015-02-21 at 2 41 07 pm](https://cloud.githubusercontent.com/assets/2963800/6316325/c0256416-b9d7-11e4-88f5-a00e81d8b8be.png)

I think the issue is here:
https://github.com/Sology/smart_listing/blob/master/app/assets/javascripts/smart_listing.coffee.erb#L36-L37

I don't know enough about your app to fix it, though.

**Comment by ljachymczyk** [comment]
Yes, all remote links within the list trigger fading. We might want to limit this only to item action buttons in future releases.

As a workaround for now, you can try to fade-in your list back at the end of your XHR JS views. I.e.:
```
$("#your_list").smart_listing().fadeLoaded()
```

**Comment by dudo** [comment]
Yeah. I just manually set the opacity on the element... same thing. This doesn't seem to be expected behavior... you should let people explicitly choose to add a class to links or ajax'd behaviors to get the fading.

Awesome gem, though. *Really* good work. If you're listing data, I can't see a reason why people wouldn't want to use this, ha. I remember a year ago or so, setting up jquery DataTables to work with remote data. It was... shit. Your choice to use kaminari, I could hug you. I owe you some beer. Cheers!

**Comment by ljachymczyk** [comment]
Limited the fading callback only to smart listing action links. This should not catch your custom links any more.

**Comment by dudo** [comment]
You rock. Thanks! Where's the 'buy you a beer' button? Link me!
