### ISSUE TITLE
Ability to create a new item when list is empty

### ISSUE THREAD

**Issue by Phitherek** [Sology/smart_listing#52]
I want to be able to create a new item when there is no data on the list yet. Right now the form just does not show up despite JS views working correctly.

**Comment by ljachymczyk** [comment]
Adding new item on empty list is definitely possible. What do you mean by "form just does not show up"?

**Comment by Phitherek** [comment]
It seems that the button that triggers the new item form only shows up when there is a table element. When there are no elements, the table is nonexistent and the triggering button just does not show up even when I define it with the new_item function.

**Comment by ljachymczyk** [comment]
`item_new` is by default designed to be used within a table. If you want to use it outside the table, you need to customize it i.e. by overwriting `smart_listing/_item_new.html.erb` partial.

Simple solution would be to show table always, even if no list items.

**Comment by Phitherek** [comment]
Ok, that' s fine with me.
