### ISSUE TITLE
Missing show-action for in-place editing

### ISSUE THREAD

**Issue by jumhh** [Sology/smart_listing#54]
I tried to add a show-action that works in-place, but I just saw, that there are several places, where I have to dig into your code:
- a new `show.js.erb`
- additions in `smart_listing.coffee.erb`
- adding `:show`to `smart_listing_item` in `helpers/smart_listing/helper.rb`
- etc...
I would appreciate just having it in your next release. Should be really simple for you :-)

The functional need is simple: I have got a lot of more fields in a data entity than I will show as table columns.

**Comment by ljachymczyk** [comment]
I'm not sure if I understand correctly, but there's already a built-in `show` action. But you are right, it wasn't mentioned in the README. I've added it there already.
