### ISSUE TITLE
CSS issue for smart_listing show action

### ISSUE THREAD

**Issue by Phitherek** [Sology/smart_listing#56]
Hello,

I' ve noticed, that automatically generated show action link has something like this in its CSS:

    a.show
        display: block !important

The issue is I did not want for it to be displayed as block, so I had to overwrite this in my CSS with more classes and another !important. This is a problem, because !important is generally a bad practice in CSS, as people can wonder why their modifications don' t just work if they oversee it or don' t look into the CSS, and also I think that it should have the same options as other actions by default - the user can then change it for their project if they want to.

**Comment by ljachymczyk** [comment]
I can't see `!important` anywhere in the smart_listing code. I'm pretty sure this CSS rule comes form somewhere else.
