### ISSUE TITLE
Custom locals for smart_listing partials

### ISSUE THREAD

**Issue by Phitherek** [Sology/smart_listing#57]
I want to be able to pass additional locals for partials used in smart_listing (for example form or list, which are passed by me in smart_listing_item or smart_listing_render). Right now it is not possible.

**Comment by GeorgeDewar** [comment]
I've just run into this as well.

**Comment by GeorgeDewar** [comment]
If it helps, I've forked the project and done this myself. It's only tested as much as it needs to be to work for my purposes, and I couldn't get the tests all running so I haven't made a pull request.

https://github.com/Datacom/smart_listing/tree/feature/locals

**Comment by ljachymczyk** [comment]
Thanks. This is now resolved by PR #70
