### ISSUE TITLE
Config not effective

### ISSUE THREAD

**Issue by gdurelle** [Sology/smart_listing#58]
Hi,

I tried to configure the default per_page through the ```SmartListing.configure``` block, with the helper and all, but it did not work. I tried to doi through Kaminari, but it does not work either !
I want a per_page to 25 but it seems stucked to 10.
Event with the page_size option (wich I have to implement manually as config does not works at all) when I click 25, it keeps 10 rows, same for 30, but it does works for 50.
This drive me crazy, 

any idea ?

**Comment by danieljacobarcher** [comment]
+1

**Comment by ljachymczyk** [comment]
This should be fixed already... Try the updated version from rubygems and let me know if it works.

**Comment by danieljacobarcher** [comment]
It's fixed in 1.1.2
