### ISSUE TITLE
Sorting with dates, through methods, ...

### ISSUE THREAD

**Issue by gdurelle** [Sology/smart_listing#59]
## 1. Methods

Right now we can sort by columns of models and joined models.
Is it possible to sort through a method ?
I tried to use an attr_reader :my_method but it does not work.

``` ruby
class Subscription < ActiveRecord::Base
   ....
  def commitment_end
    @commitment_end = start_at.advance(months: commitment_period.to_i)
  end
end
```

``` haml
        %th= smart_listing.sortable t('.end_of_commitment'), :commitment_end
```

And within sort_attributes : `[:commitment_end, 'subscriptions.commitment_end']`
## 2. Dates

When sorting dates, it seems the sort messes up like its a string and sort by alpha...

``` ruby
    smart_listing_create(:users, @users, partial: 'admin/users/listing_red',
                         array: true,
                         kaminari_options: { theme: 'bootstrap3' },
                         sort_attributes: [
                          [:start_at, 'subscriptions.start_at'],
                          [:lastname, 'lastname'],
                          [:firstname, 'firstname'],
                          [:email, 'email']
                         ],
                         default_sort: { start_at: 'desc' }
                         )
```

``` haml
        %th= smart_listing.sortable User.human_attribute_name(:lastname), :lastname
        %th= smart_listing.sortable User.human_attribute_name(:firstname), :firstname
        %th= smart_listing.sortable User.human_attribute_name(:email), :email
        %th= smart_listing.sortable t('.started_at'), :start_at
```

My _start_at_ columns seems not to be sorted at all, whereas others works ok.

**Comment by gdurelle** [comment]
I looked up a bit the code under the rock and it seems you order with sort, wich works with numbers and string, but not with complex column types.
For my single case I added this : 
``ruby 
  def apply_sorter
    return if params[:users_smart_listing].blank? || params[:users_smart_listing][:sort].blank?
    key = params[:users_smart_listing][:sort].keys.last
    order_value = params[:users_smart_listing][:sort].values.last
    order = order_value == 'asc' ? 'ASC' : 'DESC'
    return unless key == 'start_at'
    @users = @users.order("subscriptions.start_at #{order}")
  end
```
which I call right before smart_listing_create.

**Comment by ljachymczyk** [comment]
Hello @gdurelle 
Regarding your first question, you should consider using smart listing with array, not Active Record collection. Arrays can be sorted in every way you want.
Regarding second one, what do you mean by 'complex column types'? And how to sort by them?

**Comment by gdurelle** [comment]
It was such a long time ago... I guess i meant dates, datetimes, depending on the format...

**Comment by ljachymczyk** [comment]
Yup, long time. I'm cleaning up the issues.

So regular `order` won't work with dates?

**Comment by bhaveshf-cuelogic** [comment]
We had `call_back_datetime` column in one of our model.
We added one virtual attribute named `call_back_datetime_long` as below and used that vi:

`attr_accessor :callback_datetime_long`
`before_save -> { self.callback_datetime_long = self.callback_datetime.to_i }`

And in UI, we referred this newly created virtual attribute instead of actual column:
`<%= smart_listing.sortable "Callback Date".html_safe, :callback_datetime_long %>`
