### ISSUE TITLE
smart_listing_controls_for not auto-submitting when values changed

### ISSUE THREAD

**Issue by danieljacobarcher** [Sology/smart_listing#61]
@ljachymczyk I'm having some trouble getting smart_listing_controls_for to auto-submit and update the list.. From what I can tell, the HTML is rendered exactly the same as the demo on http://showcase.sology.eu/smart_listing under 'Controls Form'

Here's the code for the filter bar:
````
<%= smart_listing_controls_for(:photos, {class: "form-inline text-right"}) do %>
  <div class="form-group filter input-append">
    <%= hidden_field_tag :date_start, date_start.to_i %>
    <%= hidden_field_tag :date_end, date_end.to_i %>
  </div>
<% end %>
````

Does it make a difference if it's a `hidden_field_tag` versus a `text_field_tag`? And just to confirm, it should live outside the `smart_listing_render` partial?

**Comment by danieljacobarcher** [comment]
Found that it's conflicting with https://github.com/jordanbrock/bootstrap-daterangepicker-rails, closing issue - will figure it out separately.

**Comment by say8425** [comment]
I try to put this gem, too. What issues makes it conflict?
