### ISSUE TITLE
smart_listing_controls not auto-firing on change

### ISSUE THREAD

**Issue by danieljacobarcher** [Sology/smart_listing#62]
At the moment, AJAX UJS is not firing for me - it only works if I have a submit button and click the button - and it only works once.

I'm on v1.1.2

**Comment by ardahaal** [comment]
Hello @danieljacobarcher ,

please visit: https://smart-listing-example.herokuapp.com/ and write some names in search field. It responses automatically without reloading the page. Was that your goal?

v1.1.2

**Comment by danieljacobarcher** [comment]
@ardahaal it seems like it depends on class names and not just fields in general? I'm having a problem where check boxes being changed does not submit the form accurately. (if both unchecked, it still submits values for each of them)

**Comment by ardahaal** [comment]
@danieljacobarcher Could you provide some code? Possibly little app deployed on heroku?

**Comment by danieljacobarcher** [comment]
Figured it out and created a PR https://github.com/Sology/smart_listing/pull/66
