### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by wynksaiddestroy** [Sology/smart_listing#63]
Although the current version is 1.1.2 the changelog only covers changes up to version 1.1.0.

**Comment by ljachymczyk** [comment]
These are really just minor bugfixes. No need to put it in the changelog.

**Comment by wynksaiddestroy** [comment]
Especially #20 affected a number of people (including me). I think the mere amount of 18 comments shows the importance of the issue for those users. Therefore it would be quite helpful to be able to check the changelog for those kinds of bug fixes.
