### ISSUE TITLE
Add spinner when loading

### ISSUE THREAD

**Issue by kockok** [Sology/smart_listing#64]
It would be great if there's any loading indicators.

**Comment by ljachymczyk** [comment]
Smart Listing root container has `smart-listing` class. There are two containers inside: one with class `loading` and the other with class `content`. 
`loading` container is faded in when the content is loading. You can style it according to your needs (ie. add spinner background).

**Comment by say8425** [comment]
But how can I  use 'loading' There no how to use it.
