### ISSUE TITLE
Javascript Error: '$(SmartListing.config.class_name("main")).smart_listing()')

### ISSUE THREAD

**Issue by foureyesup** [Sology/smart_listing#65]
Hi there - I'm getting the following JS error on pageload, and it seems to be stopping everything from functioning:

    TypeError: undefined is not a function (evaluating
     '$(SmartListing.config.class_name("main")).smart_listing()')

I have followed all of the instructions, tried with and without the views, and with and without the initialiser. Is this a known issue (on Rails 4.0.0)?

**Comment by ljachymczyk** [comment]
Have you included smart_listing js in your application.js file?
