### ISSUE TITLE
problem with implicit sorting

### ISSUE THREAD

**Issue by bakai** [Sology/smart_listing#67]
I implemented impliciting sorting as advised in README. But when I click sortable table headers(which appear as link) nothing happens. If I open that link in new tab, table gets sorted. Also there is an js error: Uncaught TypeError: Cannot set property 'href' of undefined in smart_listing.js line 5

  $.rails.href = function(element) {
    return element.attr("href") || element.data("href") || window.location.pathname;
  };

**Comment by dgmcguire** [comment]
I'm having the same issue, did you ever figure it out?

**Comment by ljachymczyk** [comment]
Hi guys,
``$.rails.href = function(element) {` has to be *after* requiring jquery. So your application.js should have following order of requires:
```
//= require jquery
//= require jquery_ujs
//= require smart_listing
```
Let me know if this is the issue.

**Comment by dgmcguire** [comment]
sorry, user error.  I simply hadn't required in any JS as the page I was on was using a template that hadn't loaded the main application script.
