### ISSUE TITLE
Uncaught TypeError: smart_listing.params is not a function

### ISSUE THREAD

**Issue by marcgenou** [Sology/smart_listing#69]
Hi

I am learning rails and I've found some troubles on the way.
Js not working trying to use controls form and filters.

console shows this error if I click on checkbox or search
Uncaught TypeError: smart_listing.params is not a function

**Comment by ljachymczyk** [comment]
Have you included smart_listing js in your application.js file?

**Comment by arnebakker** [comment]
Make sure the name parameter is the same in both methods. Its the first parameter in ````smart_listing_render```` and ````smart_listing_controls````.

**Comment by mirtara** [comment]
hi people,
@arnebakker , could you give more info about your reply? I am having the same issue  but i don't understand what you mind by "Make sure the name parameter is the same in both methods. It's the first parameter in both smart_listing_render and smart_listing_controls."

I will very appreciate your help!

**Comment by mirtara** [comment]
@arnebakker nevermind! I found my issue, you were right!! I was using 
smart_listing_controls_for(:users)
<%= smart_listing_update :students %>

the parameters were different. Now i am using 

smart_listing_controls_for(:students)
<%= smart_listing_update :students %>

and it works perfectly.

Thanks for your help!

**Comment by arnebakker** [comment]
Make sure that in `smart_listing_update(:users)` and `smart_listing_controls_for(:users)` both point to the same listing. In this case `:users`.
