### ISSUE TITLE
undefined method 'active' for

### ISSUE THREAD

**Issue by amywalsh** [Sology/smart_listing#71]
Perhaps I have misunderstood how to implement ... however get the error undefined method 'active' for #<Class:........> when using smart_listing_create

@campaigns = smart_listing_create :campaigns, Campaign.active, partial: "campaigns/list"

if I change Campaign.active to Campaign.all the page renders but my list is blank.

My controller looks like this;

class CampaignsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate
  def index
    puts "index".red
    #smart_listing_create :campaigns, Campaign.all, partial: "campaigns/list"
    #@campaigns = Campaign.all
    @campaigns = smart_listing_create :campaigns, Campaign.active, partial: "campaigns/list"
  end
end

Any help would be appreciated. Thanks!

**Comment by wkurosawa** [comment]
`.active` was meant to be a scope, showing that you can use *smart_listing* with ActiveRecord scopes, but you can use `.all` without problems.

**Comment by amywalsh** [comment]
Yes, thank you...I did change this and everything is working fine!! Appreciate your time!
