### ISSUE TITLE
In-place editing deletion with a form

### ISSUE THREAD

**Issue by AnthonyDeSimone** [Sology/smart_listing#72]
I'm trying to remove an item from a table, but I need a form to allow the user to submit a reason for removing the item. Is there an easy way to combine the UX of rendering a form like the "edit" examples and then removing the row when they submit that form like the "delete" example?

**Comment by ardahaal** [comment]
I think quickest way to do this would be editing `confirmation` with some content_tags in https://github.com/Sology/smart_listing/blob/master/app/views/smart_listing/_action_delete.html.erb
After that when item is being removed form the list You can setup an event on `"smart_listing:remove"` and saving in Your db or wherever You like this reason for deleting an item. Does that sound ok?

BTW I'm so sorry for this delayed answer.

**Comment by AnthonyDeSimone** [comment]
Thanks! That looks like a good solution.
