### ISSUE TITLE
Getting joined record data after sort

### ISSUE THREAD

**Issue by amisle** [Sology/smart_listing#73]
I have a one-to-many relation with my models, so I have setup an explicit sort in my widgets_controller:

smart_listing_create(:widgets, Widget.all.joins(:cogs), partial: "widgets/list", default_sort: {inventory_number: "asc"}, sort_attributes: [[:cog_height, "cogs.cog_height"], [:cog_width, "cogs.cog_width"]])

It works great and I get multiple entries in the list for each Widget with multiple Cogs. Each inventory number is listed X number of times if the widget has X cogs associated. This is good!

But how do I show the correct Cog height and width alongside each inventory number entry? For example, in my _list partial:

<% smart_listing.collection.each do |w| %>
        &lt;tr&gt;
          &lt;td&gt;<%= w.inventory_number %>&lt;/td&gt;
          &lt;td&gt;<%= w.[????].cog_height %>&lt;/td&gt;
          &lt;td&gt;<%= w.[????].cog_width %>&lt;/td&gt;
        ...

Where [????] is, I need some way to get a reference to the current Cog model being listed there. How do I do that? If my example doesn't make sense, please let me know. And apologies in advance if I am missing something obvious. Thanks!

**Comment by ardahaal** [comment]
Hello, thanks for using smart_listing.
If I understand this correctly, I think this should work just right:

    <% smart_listing.collection.each do |w| %>
    <tr>
    <td><%= w.inventory_number %></td>
    <td><%= w.cog.cog_height %></td>
    <td><%= w.cog.cog_width %></td>
    ...

Or You could use `delegate` method in Your model.

If I don't understand it correctly let me know.

**Comment by amisle** [comment]
This would work if I was listing cogs in my example, but unfortunately I am looking at the other side of the relation. For example, this would work if I redid the controller similarly:

```
<% smart_listing.collection.each do |c| %>
<tr>
<td><%= c.widget.inventory_number %></td>
<td><%= c.cog_height %></td>
<td><%= c.cog_width %></td>
...
```

Is there any other way you can think of coming from the one side of the one-to-many relation, rather than the many side? Delegates are good to know about, but again I don't think they will help me here.

**Comment by ljachymczyk** [comment]
I think this is more Ruby on Rails query methods question. You may try to use `select` to explicitly specify columns from joined table to select with some aliases and then these aliases should be available as model object attributes.
