### ISSUE TITLE
Edit function does not work in my use-case

### ISSUE THREAD

**Issue by wytzejan** [Sology/smart_listing#80]
I am working with the smart_listing gem in my application but unfortunately the edit function does not work. When I click on the edit function nothing happens. I can see the output in the console is correct (see below). Can you see in the code if I do anything incorrectly?

**Output console**

Started GET "/churches/36/edit" for ::1 at 2016-02-23 22:12:01 +0100
Processing by ChurchesController#edit as JS
  Parameters: {"id"=>"36"}
  Church Load (1.0ms)  SELECT  "churches".\* FROM "churches" WHERE "churches"."subdomain" IS NULL  ORDER BY "churches"."id" ASC LIMIT 1
  Church Load (1.0ms)  SELECT  "churches".\* FROM "churches" WHERE "churches"."id" = ? LIMIT 1  [["id", 36]]
  Rendered churches/_form.html.erb (3.0ms)
  Rendered smart_listing/item/_edit.js.erb (46.1ms)
  Rendered churches/edit.js.erb (93.2ms)
Completed 200 OK in 232ms (Views: 219.4ms | ActiveRecord: 2.0ms)

**Controller**

```
class ChurchesController < ApplicationController

  before_filter :set_church, except: [:index, :new, :create]

  def index
    smart_listing_create :churches, Church.all, partial: "churches/list"
  end

  def new
    @church = Church.new
  end

  def create
    @church = Church.create(church_params)
  end

  def edit
  end

  def update
    @church.update_attributes(church_params)
  end

  def destroy
    @church.destroy
  end

  private
    def set_church
      @church = Church.find(params[:id])
    end

    def church_params
      params.require(:church).permit(:id, :name, :subdomain, :logo)
    end
end
```

**Partial _church.html.erb**

```
<td>
  <%= link_to object.name, object %>
</td>
<td>
  <%= object.subdomain %>
</td>
<td class="actions">
  <%= smart_listing_item_actions [
    {name: :show, url: church_path(object)},
    {name: :edit, url: edit_church_path(object)},
    {name: :destroy, url: church_path(object), confirmation: "Are you sure you want to delete this?"}
    ] %>
</td>
```

**Partial _form.html.erb**

```
<td colspan="3">
  <%= form_for object, url: object.new_record? ? churches_path : church_path(object), remote: true, html: { :class => "form-horizontal" } do |f| %>
    <form class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-2 control-label">Naam</label>
        <div class="col-sm-10">
          <%= f.text_field :name, class: "form-control input", placeholder: "Naam" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Subdomein</label>
        <div class="col-sm-10">
          <%= f.text_field :subdomain, class: "form-control input", placeholder: "Subdomein" %>
        </div>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
      <button class="btn btn-link cancel">Cancel</button>
    </form>
  <% end %>
</td>
```

**Partial _list.html.erb**

```
<% unless smart_listing.empty? %>
  <table class="table table-striped">
    <thead>
      <th>Organisatie</th>
      <th>Domeinnaam</th>
      <th class="col-md-1"></th>
    </thead>
    <tbody>
      <% smart_listing.collection.each do |o| %>
        <tr class="editable" data="<%= {id:(o.id)} %>">
          <%= smart_listing.render object: o, partial: "churches/church", locals: {object: o} %>
        </tr>
      <% end %>
      <%= smart_listing.item_new colspan: 3, link: new_church_path %>
    </tbody>
  </table>
<% else %>
<table class="table table-striped">
    <thead>
      <th></th>
    </thead>
    <tbody>
      <%= smart_listing.item_new colspan: 3, link: new_church_path %>
    </tbody>
  </table>
<% end %>
<%= smart_listing.paginate %>
<%= smart_listing.pagination_per_page_links %>
```

**Comment by ljachymczyk** [comment]
Please check the JS ajax response you get and evaluate it in the console. If it causes and error, you'll see it.

**Comment by foxmuldercp** [comment]
I see this issue too.
no error in app console. in chrome/ms edge development console
in js body in development console see only this:
var smart_listing = $('#domains').smart_listing();
smart_listing.edit(ffd5feb2-b8ac-434e-b0e5-029352b7a4cb, "<td>test<\/td>\n"); received from be erb ot haml templates
and in main window contend goes to background, as for modal windows opened, but nothing, I don't see my <td>test </test> into row of my editable object

**Comment by foxmuldercp** [comment]
Try to create new rails 5 app on same server, with your code provided in 
http://showcase.sology.eu/smart_listing

use bootstrap-sass, smart_listing only gems.

partial tests seems passed - my simple form opens for editing properly

I use integer as record in and sqlite for database.

In my production app from prevoius comment where edit/update actions failed to show after fadeIn - i use postgresql UUIDs as record identifiers and drop turbolinks from Gemfile. may be problem in this damaged requirements?

**Comment by ljachymczyk** [comment]
@foxmuldercp I don't think you have the same problem as @wytzejan 

SmartListing doesn't support UUID record identifiers as you can see above:
`smart_listing.edit(5f3cf870-f87e-4178-b604-6e0df657b85c, "my long content here<\/td>\n");`
is syntax error (5f3cf870-f87e-4178-b604-6e0df657b85c instead of simple int).

If you like us to include such feature, please open separate ticket or submit a pull request.

**Comment by fatihtas** [comment]
any updates on this? i am having same problem. 
new action works, but not edit action. it fades in and thats it. 200, successful answer from server, templates are fine as well. + turbolinks disabled. 
no idea whats wrong.

**Comment by ljachymczyk** [comment]
Can you get the response body of XHR request, paste it into your JS console and execute please?

**Comment by fatihtas** [comment]
hey man, 

thanks for the tip!. 
it gives and invalid/unexpected token in that case, and here is my response: 

`var smart_listing = $('#variants').smart_listing();`
`smart_listing.edit(5a74dbeb1abe263777000001, "<td colspan=\'10\'>\n  <form enctype=\"multipart/form-data\" class=\"form-horizontal\" id=\"edit_variant_5a74dbeb1abe263777000001\" action=\"/tr/companies/nur-abla-karadeniz-sofrasi/products/kara-lahana-corbasi-nur-abla-karadeniz-sofrasi-umraniye-alemdag/variants/5a74dbeb1abe263777000001\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"><input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" /><input type=\"hidden\" name=\"_method\" value=\"patch\" />  <div class=\'col-xs-6\'>\n      <label for=\"variant_title\">Title <\/label>\n      <input type=\"text\" value=\"var 2\" name=\"variant[title]\" id=\"variant_title\" />\n      <br>\n    <\/div>\n    <div class=\'col-xs-6\'>\n      <label for=\"variant_director\">Director <\/label>\n      <input type=\"text\" value=\"merve durmaz\" name=\"variant[director]\" id=\"variant_director\" />\n      <br>\n    <\/div>\n    <hr>\n    <div class=\'col-xs-3\'>\n      <input type=\"submit\" name=\"commit\" value=\"Save\" class=\"btn btn-primary\" />\n    <\/div>\n    <button class=\'cancel btn btn-link\'>Cancel<\/button>\n  <\/form>\n<\/td>\n");`



but when i try it for new action, it works fine and also in the console.

**Comment by Syanara17** [comment]
I had the same problem but for me the issue was that I misspelled the .editable class selector...

For folks like me I just want to note, please check your class spellings
