### ISSUE TITLE
Sort does not work if i have `//= require jquery_ujs` 

### ISSUE THREAD

**Issue by alexwiththescar** [Sology/smart_listing#85]
For some reason that i just cant figure out, unless i remove `//= require jquery_ujs`from application.js the Sort headers do not work. 

But obiously if i remove `//= require jquery_ujs` then other bits of my app break.

What have i missed?

Any ideas?

Thanks in advance.

using 
jquery-rails-4.1.1
rails-4.2.4

**Comment by ACPK** [comment]
@alexwiththescar - Is this still an issue?

**Comment by alexwiththescar** [comment]
Yea, Still having no joy, cant figure out why

**Comment by ljachymczyk** [comment]
Smart Listing requires jquery_ujs to work properly. Any errors in your JS console?

**Comment by srinivasv-ttweb** [comment]
Uncaught TypeError: Cannot set property 'href' of undefined
