### ISSUE TITLE
Multiselects do not send multiple params

### ISSUE THREAD

**Issue by rexmadden** [Sology/smart_listing#87]
If you have a multiselect, only the last value selected is sent to the controller.

`select_tag :company, ... , multiple: true`

My best guess is that this code in the javascript is overwriting the params. Unfortunately I ran out of time to figure it out for sure.

``` javascript
    $.each(controls.serializeArray(), function(i, field) {
        return prms[field.name] = field.value;`
     });
```

**Comment by mahendhar9** [comment]
Check this [http://stackoverflow.com/questions/36729489/rails-pass-multiple-checkbox-values-through-params](http://stackoverflow.com/questions/36729489/rails-pass-multiple-checkbox-values-through-params)
