### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by dgleba** [Sology/smart_listing#88]
I am looking for an example app. I am having trouble getting started and it would help if I could look at a full working example project.

I have tried to use the code snippets from the show case but I am getting a error.

```
undefined method `max_count' for nil:NilClass
```

```
_app_views_rental_records_index_html_erb___4152771273386268294_70148448699060
app/views/rental_records/index.html.erb
1 2 3
<% # Render list %>
<%= smart_listing_render :rental_records %>
```

Can someone please point me to an example project?

**Comment by ardahaal** [comment]
Hello @dgleba 
Here you can find code with set up heroku:
https://github.com/ardahaal/smart_listing_example
https://smart-listing-example.herokuapp.com/
