### ISSUE TITLE
The new form is not showed correcly

### ISSUE THREAD

**Issue by GCorbel** [Sology/smart_listing#9]
I'm trying to use this : 

```
<%= smart_listing_item :sightings, :new, @sighting, "sightings/form" %>
```

The form is a simple form but the result appenned is something like `<form></form>fields`. I made some test and I have this result : 

```
$('table').first().html('<form>a</form>')
$('table').first().html() // return "<form></form>a"
$('.content').first().html('<form>a</form>')
$('.content').first().html() // return "<form>a</form>"
```

The first case is correct and the second is not. All childs of 'table' do the samething. I am using the latest version of twitter-bootstrap, rails, etc.

It do the same thing with Chrome and Firefox.

I don't have any idea. Do you have a solution?

Thanks.

**Comment by ericboehs** [comment]
I had this exact problem. Might be good to point it out in the readme.
