### ISSUE TITLE
Save only works with turbolinks activated

### ISSUE THREAD

**Issue by leahpleurodon** [Sology/smart_listing#91]
Hello thanks for the great gem,

I'm having an issue where I have put the smart list into a show.html.erb of a parent model and it will not save unless I have turbolinks turned on, however I can't have turbolinks on as it breaks my js. -> Now that I have done soe fiddling I've found another issue where when I click save on creation of a new model it refreshes my page.

**Comment by ljachymczyk** [comment]
Smart Listing is proven to work just fine without turbolinks. Please provide some more details if you want me to help you.
