### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by rush-skills** [Sology/smart_listing#92]
I tried setting up smart_listing in one of my models inside a Rails 5 app and it didn't work with pagination, running into #79. I just wanted to know if rails 5 is officially supported or is there any new version in the roadmap adding rails 5 support.

**Comment by akostadinov** [comment]
It btw also fails with sorting but #98 should have it fixed. I'm wondering if project maintainer is still active.

**Comment by ljachymczyk** [comment]
@akostadinov I'm alive! But a bit busy lately...

@rush-skills Can you check if https://github.com/Sology/smart_listing/pull/98 works for you?

**Comment by rush-skills** [comment]
#98 Worked for me. Still struggling to integrate this with [jgthms/bulma](https://github.com/jgthms/bulma) 😁
