### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by robyurkowski** [Sology/smart_listing#94]
I've an application that benefits from the addition of locals to list rendering, and it took me a bit of time to realize that this was unreleased even though it was written at the start of the year.

For now, I'm very happy to just specify the SHA of the latest commit, but it'd be nice in terms of stability to be able to peg to version 1.2 or 1.1.3. Would you consider releasing a new version?

**Comment by ljachymczyk** [comment]
@robyurkowski 
Yes, I'll release new version as soon as I'm sure it works with Rails 5 (https://github.com/Sology/smart_listing/pull/98). Need to find time to make some tests.

**Comment by ljachymczyk** [comment]
Hi @robyurkowski 
The release is out. Check it!

**Comment by robyurkowski** [comment]
Awesome, thanks!
