### ISSUE TITLE
Order not guaranteed when sorting on non-unique fields

### ISSUE THREAD

**Issue by AnthonyDeSimone** [Sology/smart_listing#95]
When sorting records on a column that is not unique, there is no guarantee of the order of those records without specifying a secondary sort field. This creates a big issue with pagination. The most obvious solution to me seems to be using the record id as a secondary. I can't find any non-hacky way of doing this. Are there any options I'm missing?

**Comment by ljachymczyk** [comment]
This requires Smart Listing to support sort by multiple columns - requested in #7 

Currently this is not supported yet.

**Comment by AnthonyDeSimone** [comment]
This really isn't a feature request. It's a hard requirement for library dealing with pagination. 

Fortunately I did finally discover a workaround. By providing the sort_attributes argument to `smart_listing_create`, we can order by multiple columns:
