### ISSUE TITLE
allow setting confirmation placement

### ISSUE THREAD

**Issue by akostadinov** [Sology/smart_listing#97]
I have the following actions:
```
%td.actions= smart_listing_item_actions [{name: :edit, url: edit_lock_path(object)}, {name: :destroy, url: lock_path(object), confirmation: "Are you sure you want to delete this lock?"}]
```
Issue is that clicking the delete icon results in a box appearing to the right of the item so user easily would not notice anything appeared there at all. Also user has to scroll to be able to confirm. Ideally one should be able to set placement of confirmation.

**Comment by akostadinov** [comment]
Ideally https://github.com/Sology/smart_listing/blob/master/app/helpers/smart_listing/helper.rb would be modified to also read user parameter of `placement` for the delete action.

I have worked around the issue by modifying `app/views/smart_listing/_action_delete.html.erb` template in my app to include `:placement => "auto"` next to `:confirmation => ...`.

Regards.

**Comment by ljachymczyk** [comment]
Yes, You did the right thing (tm). 

You can also overwrite the $.fn.smart_listing.showConfirmation JS function to include some custom behaviour.
