### ISSUE TITLE
 warning: duplicated key at line 79 ignored: :href

### ISSUE THREAD

**Issue by sutherland007** [Sology/smart_listing#99]
When run rails `generate smart_listing:install` throws this warning

`C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/smart_listing-1.0.0/lib/smart_listing/config.rb:73: warning: duplicated key at line 79 ignored: :href`

The file has been generated but, when i run other command like `rake:db migrate`for example that warning is appearing.

My rails version is 4.2.6
My ruby version is 2.2.0
Hope it helps.

**Comment by wynksaiddestroy** [comment]
I think this was solved in #43. As I can see in your error message you're still using version 1.0.0.
Could you please update to the latest version (1.2.0) and report back whether the warning still appears? Thanks.
